[package]
name = "backend"
version = "0.2.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.6.0"
actix-web-lab = "0.20.2"
actix-cors = "0.7.0"
actix-ws = "0.2.5"
actix-governor = "0.5.0"
actix-multipart = "0.6.1"

tokio = { version = "1.37.0", default-features = false }

once_cell = "1.19.0"
url = { version = "2.5.0", features = ["serde"] }

rusty-s3 = "0.5.0"

serde = "1.0.202"
serde_json = "1.0.117"
serde_with = "3.8.1"

sqlx = { version = "0.7.4", features = [
    "mysql",
    "runtime-tokio",
    "tls-rustls",
    "chrono",
] }
sha2 = "0.10.8"
base64 = "0.22.1"
password-auth = "1.0.0"
cuid2 = "0.1.2"
snowflaked = "1.0.3"

thiserror = "1.0.61"
dotenvy = "0.15.7"
futures = "0.3.30"

chrono = { version = "0.4.38", features = ["serde"] }
validator = { version = "0.18.1", features = ["derive"] }
ts-rs = { version = "8.1.0", features = ["chrono-impl", "url-impl"] }

sentry = "0.32.3"
sentry-log = "0.32.3"
sentry-actix = "0.32.3"
log = "0.4.21"
pretty_env_logger = "0.5.0"
indexmap = "2.2.6"
dashmap = { version = "5.5.3", features = ["inline"] }
