name: biasdo-backend
services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
  db:

networks:
  backend:
    driver: bridge
