packages:
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  svelte-preprocess: true

patchedDependencies:
  svelte-virtual-scroll-list@1.3.0: patches/svelte-virtual-scroll-list@1.3.0.patch
  carta-md@4.6.7: patches/carta-md@4.6.7.patch
  svelte-portal@2.2.1: patches/svelte-portal@2.2.1.patch
