name: biasdo-server
services:
  mysql:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - backend
    restart: unless-stopped

#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'
#    networks:
#      - backend
#    restart: unless-stopped

networks:
  backend:
    driver: bridge
