app = "biasdo-server"
primary_region = "waw"

kill_signal = "SIGINT"
kill_timeout = 5

[build.args]
DATABASE_URL = "mysql://root:QekY7YNkWasy9aLugVAvofgDxc9NuvdtMXYMWNku8wpJPK5x@biasdo-maria.internal:3306/biasdo"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
DATABASE_URL = "mysql://root:QekY7YNkWasy9aLugVAvofgDxc9NuvdtMXYMWNku8wpJPK5x@biasdo-maria.internal:3306/biasdo"
ADDRESS = "0.0.0.0"
PORT = "8080"
