// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelKind } from "./ChannelKind";
import type { Id } from "./Id";

export interface Channel { id: Id, created_at: string, name: string, kind: ChannelKind, server_id: Id, }