// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Client = { id: `${number}`, name: string, owner_id: `${number}`, client_uri: string | null, tos_uri: string | null, policy_uri: string | null, redirect_uris: Array<string>, };