// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Server } from "./Server";

export type Invite = { id: string, server: Server, created_at: string, expires_at: string, };