// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export interface Invite { id: Id, created_at: string, expires_at: string, server_id: Id, }