// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { OptionId } from "./OptionId";

export interface Member { id: Id, created_at: string, server_id: Id, user_id: OptionId, nickname?: string, }