// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { MessageKind } from "./MessageKind";
import type { OptionId } from "./OptionId";

export interface Message { id: Id, created_at: string, content: string, kind: MessageKind, channel_id: Id, user_id: OptionId, }