// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageKind } from "./MessageKind";
import type { ServerMember } from "./ServerMember";
import type { User } from "./User";

export type Message = { id: `${number}`, kind: MessageKind, updated_at: string | null, content: string, channel_id: `${number}`, user: User, member: ServerMember | null, };
