// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadWrite } from "./ReadWrite";

export type Scope = { "Profile": ReadWrite } | { "Servers": ReadWrite } | { "Messages": ReadWrite } | { "Friends": ReadWrite };