// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export interface Server { id: Id, created_at: string, name: string, owner_id: Id, }