// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type ServerMember = { user_id: `${number}`, server_id: `${number}`, created_at: string, nickname: string | null, user: User | null, };