// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type UserFriendRequest = { sender: User, receiver: User, created_at: string, };