// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { User } from "./User";

export type UserFriend = { user: User, friend: User, created_at: string, channel: Channel, };